

###

GET http://127.0.0.1:5000/ HTTP/1.1
content-type: application/json


###

POST http://127.0.0.1:5000/flow HTTP/1.1
content-type: application/json

{
    "flow": "Get home data now!!",
    "params": {
        "xx": "123"
    }
}

###


